### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [rrrayyy/prj-rev-bwfs-tea-cozy#5]
_Grade:_ **Meets Expecations**

Nice work creating a web page that implements the project specification.

It is clear that you have a good grasp of the difference between identifiers and classes, and how each are used.

Your source code (both HTML and CSS) are reasonably formatted -- do pay attention to the detail though, and be consistent with spacing, and avoiding excessive blank lines.

Keep the code _concise, readable, and duplication-free_. This includes removing empty rules from the CSS. 

Further reading:
* https://learn.shayhowe.com/html-css/writing-your-best-code/

Keep up the good work!

**Comment by rrrayyy** [comment]
It good to know that I am dropping off some of the details.
And also thank you for the further learning material.
